### ISSUE TITLE
WebSocket 인증을 위해 STOMP 적용

### ISSUE THREAD

**Issue by Across826** [FC-Chilli-Bubble/back-officener#136]
handshake 시 인증 헤더 사용을 위해서 STOMP , SockJs 추가 리팩토링

- [x] STOMP 엔드포인트, 보안, 브로커 설정
- [x] STOMP 보안을 위한 ChannelInterceptor 구현
- [ ] 메시지 전송

**Comment by JoonheeJeong** [comment]
Raw WebSocket을 이용하고 핸드셰이킹 시 쿼리파라미터로 JWT를 받는 방식으로 문제를 잠정 해결하였습니다. 따라서 본 이슈는 보류합니다.
